### ISSUE TITLE
Terraform crashing when using the v0.1.2 of the provider

### ISSUE THREAD

**Issue by bogdan-grozoiu** [akamai/terraform-provider-akamai#23]
### Terraform Version
Terraform v0.12.5
Akamai Provider v0.1.2

### Affected Resource(s)
Terraform.

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.12"
}

# Initialize the Akamai provider
provider "akamai" {
  version = "0.1.2"
  edgerc = "~/.edgerc"
  dns_section = "default"
}

resource "akamai_dns_record" "acc_companydomain_com-txt" {
  zone       = var.zone
  name       = "acc.companydomain.com"
  recordtype = "TXT"
  ttl        = var.default_ttl
  active     = true
  target = ["Text"]
}
```

### Expected Behavior
Terraform using the Akamai provider v.0.1.2 to not crash and provision the DNS record

### Actual Behavior
Terraform crashed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "akamai" (terraform-providers/akamai) 0.1.2...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

2. `terraform plan`

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # akamai_dns_record.acc_companydomain_com-txt will be created
  + resource "akamai_dns_record" "acc_companydomain_com-txt" {
      + active     = true
      + id         = (known after apply)
      + name       = "acc.companydomain.com"
      + recordtype = "TXT"
      + target     = [
          + "Text",
        ]
      + ttl        = 3600
      + zone       = "acc.companydomain.com"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

```

3. `terraform apply`

```

akamai_dns_record.acc_companydomain_com-txt: Creating...

Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is nil, not string
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: 
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: goroutine 20 [running]:
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/akamai.checkBasicRecordTypes(0xc000288a80, 0x3, 0x1d09cb3)
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/akamai/resource_akamai_dns_record.go:920 +0x377
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/akamai.validateRecord(0xc000288a80, 0x1d105f5, 0xa)
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/akamai/resource_akamai_dns_record.go:886 +0xb1
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/akamai.resourceDNSRecordCreate(0xc000288a80, 0x1b0c4c0, 0x2922cc0, 0x2, 0x2924340)
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/akamai/resource_akamai_dns_record.go:247 +0x112
2019-07-31T15:22:10.653+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00011f680, 0xc0001c4500, 0xc00000d720, 0x1b0c4c0, 0x2922cc0, 0xc0000d9d01, 0xc00008c640, 0x1b96b60)
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x3b4
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00011f980, 0xc000093a58, 0xc0001c4500, 0xc00000d720, 0xc0003dcaa8, 0xc0003e2010, 0x1b98c00)
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ea50, 0x1f8ca60, 0xc00040b020, 0xc0000a6780, 0xc00000ea50, 0xc00040b020, 0xc0004f1bd0)
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:889 +0x9ac
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1ccdae0, 0xc00000ea50, 0x1f8ca60, 0xc00040b020, 0xc0001c4190, 0x0, 0x1f8ca60, 0xc00040b020, 0xc0000dfc00, 0x400)
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3217 +0x23e
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001e00, 0x1f98420, 0xc000072900, 0xc000414000, 0xc0003116e0, 0x28f8f80, 0x0, 0x0, 0x0)
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/vendor/google.golang.org/grpc/server.go:966 +0x470
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000001e00, 0x1f98420, 0xc000072900, 0xc000414000, 0x0)
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/vendor/google.golang.org/grpc/server.go:1245 +0xd25
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: github.com/terraform-providers/terraform-provider-akamai/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000038100, 0xc000001e00, 0x1f98420, 0xc000072900, 0xc000414000)
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/vendor/google.golang.org/grpc/server.go:685 +0x9f
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4: created by github.com/terraform-providers/terraform-provider-akamai/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-07-31T15:22:10.654+0200 [DEBUG] plugin.terraform-provider-akamai_v0.1.2_x4:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-akamai/vendor/google.golang.org/grpc/server.go:683 +0xa1
2019/07/31 15:22:10 [DEBUG] akamai_dns_record.acc_companydomain_com-txt: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/07/31 15:22:10 [TRACE] EvalMaybeTainted: akamai_dns_record.acc_companydomain_com-txt encountered an error during creation, so it is now marked as tainted
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/07/31 15:22:10 [TRACE] EvalWriteState: removing state object for akamai_dns_record.acc_companydomain_com-txt
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2019/07/31 15:22:10 [TRACE] EvalApplyProvisioners: akamai_dns_record.acc_companydomain_com-txt has no state, so skipping provisioners
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/07/31 15:22:10 [TRACE] EvalMaybeTainted: akamai_dns_record.acc_companydomain_com-txt encountered an error during creation, so it is now marked as tainted
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/07/31 15:22:10 [TRACE] EvalWriteState: removing state object for akamai_dns_record.acc_companydomain_com-txt
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalIf
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalIf
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2019/07/31 15:22:10 [TRACE] <root>: eval: *terraform.EvalApplyPost
2019/07/31 15:22:10 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2019/07/31 15:22:10 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/07/31 15:22:10 [TRACE] [walkApply] Exiting eval tree: akamai_dns_record.acc_companydomain_com-txt
2019/07/31 15:22:10 [TRACE] vertex "akamai_dns_record.acc_companydomain_com-txt": visit complete
2019/07/31 15:22:10 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/07/31 15:22:10 [TRACE] dag/walk: upstream of "provider.akamai (close)" errored, so skipping
2019/07/31 15:22:10 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019/07/31 15:22:10 [TRACE] statemgr.Filesystem: reading latest snapshot from terraform.tfstate
2019-07-31T15:22:10.655+0200 [DEBUG] plugin: plugin process exited: path=/Users/bgrozoiu/Documents/UNPUBLISHED/akamai/.terraform/plugins/darwin_amd64/terraform-provider-akamai_v0.1.2_x4 pid=14416 error="exit status 2"
2019/07/31 15:22:10 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2019/07/31 15:22:10 [TRACE] statemgr.Filesystem: read nil snapshot
2019/07/31 15:22:10 [TRACE] statemgr.Filesystem: no original state snapshot to back up
2019/07/31 15:22:10 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 1
2019/07/31 15:22:10 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2019/07/31 15:22:10 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/07/31 15:22:10 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2019-07-31T15:22:10.677+0200 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by dshafik** [comment]
This issue has been fixed and will be included in the  next provider release

**Comment by alex-3sr** [comment]
Hi,

Does we have an estimation for the next provider release ?
Or, are there a workaround for use the fix before waiting next release ?

Thanks,
Alexandre

**Comment by alex-3sr** [comment]
Hi,

U can ignore my question ^^ Finally, I deleted the subfolder plugin on my terraform folder, and new plugin 0.1.3 was downloaded successfully and now able to add new DNS record again ;)

Thx
Alexandre

**Comment by melissabrooksQHR** [comment]
Hi,

I am still getting this same error using 0.1.3. 

I tried deleting my terrafrom folder and re initializing with the same result. 

```
terraform -v
Terraform v0.12.17
+ provider.akamai v0.1.3
```
Any ideas? 

Thanks,
Melissa
