### ISSUE TITLE
dataset_fields_ids should not be ordered

### ISSUE THREAD

**Issue by Fuochi** [akamai/terraform-provider-akamai#287]
Hi @robertolopezlopez.
Unfortunately, I feel that either the documentation or the implementation is wrong. I still haven't checked which one.
It doesn't seem to matter in which order you write the dataset_fields_ids in the TF resource, the read will always return them in the same order, as written in the pr description.

_Originally posted by @Fuochi in https://github.com/akamai/terraform-provider-akamai/issues/274#issuecomment-1036190886_

**Comment by robertolopezlopez** [comment]
Hi @Fuochi ,

Thank you for following up here, we will be able to address the problem better. Could you please share with us the HCL configuration and steps to be able to reproduce [your problem](https://github.com/akamai/terraform-provider-akamai/pull/274#issue-1096165404)?

Thanks :-)

**Comment by Fuochi** [comment]
Hi @robertolopezlopez,
you can use your own example from docs, just add multiple ids:
```hcl
resource "akamai_datastream" "stream" {
    active             = false
    config {
        delimiter          = "SPACE"
        format             = "STRUCTURED"
        frequency {
            time_in_sec = 30
        }
        upload_file_prefix = "pre"
        upload_file_suffix = "suf"
    }
    contract_id        = "2-FGHIJ"
    dataset_fields_ids = [
        1002, 1005, 1006, 1008, 1009, 1100
    ]
    email_ids          = [
        "test@akamai.com",
        "test2@akamai.com"
    ]
    group_id           = 12345
    property_ids       = [
        100011011
    ]
    stream_name        = "Test data stream"
    stream_type        = "RAW_LOGS"
    template_name      = "EDGE_LOGS"

    s3_connector {
        access_key        = "1T2ll1H4dXWx5itGhpc7FlSbvvOvky1098nTtEMg"
        bucket            = "datastream.akamai.com"
        connector_name    = "S3Destination"
        path              = "log/edgelogs"
        region            = "ap-south-1"
        secret_access_key = "AKIA6DK7TDQLVGZ3TYP1"
    }
}
```
apply it twice or more, and you'll always see that the order trigger a change.
Thanks

**Comment by robertolopezlopez** [comment]
Thank you @Fuochi , I wasn't much involved in the development of this subprovider - but I will check and share my thoughts ;-)

**Comment by robertolopezlopez** [comment]
@Fuochi : which provider version? Given the timing of your PR, can I assume that it was 1.9.1?

**Comment by robertolopezlopez** [comment]
Hi,

I have used the following config:

```hcl
terraform {
  required_providers {
    akamai = {
      source = "akamai/akamai"
      version = "1.9.1"
    }
  }
}

provider "akamai" {
    edgerc = "~/.edgerc"
    config_section = "cloud_shared_datastream"

}

resource "akamai_datastream" "stream" {
    active             = false
    config {
        delimiter          = "SPACE"
        format             = "STRUCTURED"
        frequency {
            time_in_sec = 30
        }
        upload_file_prefix = "pre"
        upload_file_suffix = "suf"
    }
    contract_id        = "1-MASKED"
    dataset_fields_ids = [
        1002, 1005, 1006, 1008, 1009, 1100
    ]
    email_ids          = [
        "test@akamai.com",
        "test2@akamai.com"
    ]
    group_id           = 17324
    property_ids       = [
        200512074
    ]
    stream_name        = "Test data stream - test roberto gh issue 287"
    stream_type        = "RAW_LOGS"
    template_name      = "EDGE_LOGS"

    s3_connector {
        access_key        = "---MASKED---"
        bucket            = "---MASKED---"
        connector_name    = "S3Destination"
        path              = "---MASKED---"
        region            = "ap-south-1"
        secret_access_key = "---MASKED---"
    }
}
```

![image](https://user-images.githubusercontent.com/1519467/154493591-6f7a49b0-50ce-4902-8188-f5eb72beb735.png)
![image](https://user-images.githubusercontent.com/1519467/154493893-10a5dd24-da8a-4c78-becf-d477d1fa0d61.png)

Initial creation seems correct. Then, if I do not change anything and enter `terraform apply` once again...

![image](https://user-images.githubusercontent.com/1519467/154494168-3d67fe5c-93f7-47c1-b647-c287bd828398.png)

Same results with the latest version of the provider (1.10.1).

I guess that I am missing something here. Could you please tell me to reproduce this problem locally? Thanks :-)

Kind regards,

Roberto

**Comment by robertolopezlopez** [comment]
I have also tried with more IDs:

> 1002, 1006, 1008, 1011, 1012, 1013, 1017, 1032, 1033, 1068, 1100, 1102, 1103, 2007, 2008, 2009, 2010

No change so far, 0 diff on second apply

**Comment by robertolopezlopez** [comment]
> @Fuochi : which provider version? Given the timing of your PR, can I assume that it was 1.9.1?

Could you please share the concrete version of provider which you are using? Looking at the changelog of 1.9.0, there was a fix regarding ordering of this precise schema attribute.

![image](https://user-images.githubusercontent.com/1519467/154500996-4313a073-7943-46ec-a877-e39ec686d72a.png)

And I have actually got the above diff when testing with 1.8.0. Could you please confirm that this is your provider version? In such case, I can say with confidence that this issue has been fixed since 1.9.0.

Related:
* https://github.com/akamai/terraform-provider-akamai/releases/tag/v1.9.0
* https://github.com/akamai/terraform-provider-akamai/issues/263

Regards,

Roberto

**Comment by Fuochi** [comment]
Hi @robertolopezlopez,
Unfortunately, I am still experiencing the issue. I just tried again with provider version 1.10.1 and terraform version 1.1.6.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/4720478/154620078-388bb3bb-9799-463e-8e59-aa9c582708fa.png">

I still receive this output after multiple terraform apply:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/4720478/154619699-6223e088-c255-42e6-bdd6-bb8aeb17688f.png">
the ids I've used  are the one provided:
```
dataset_fields_ids = [1002, 1005, 1006, 1008, 1009, 1100]
```
Do you have any suggestion?

**Comment by robertolopezlopez** [comment]
@Fuochi : thanks for sharing these extra details. Which approach did you follow after getting the error initially with 1.8.0? For example:

* `terraform destroy`
* Edit your HCL and change version from 1.8.0 to newest (i.e. 1.10.1)
* `terraform init`
* `terraform apply`
* `terraform apply`

Or did you rather do the following:

* Edit HCL and change version from 1.8.0 to newest.
* `terraform apply`
* ?

I suspect that version 1.8.0 may have been cached. Just guessing. Please answer to the question above and share with us a screenshot of your `terraform init` command, just to be sure. Thanks :-)

A fresh test (in a new directory, with a recent TFP version) may be also useful.

Regards,

Roberto

**Comment by Fuochi** [comment]
Hi @robertolopezlopez,
Sorry for my late reply. Here the full process:
1- terraform init:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4720478/154947032-177c4237-a9b7-49f7-970e-90909b1953c4.png">
2- terraform apply
<img width="650" alt="image" src="https://user-images.githubusercontent.com/4720478/154947445-11d15f50-2390-4f2d-99d4-2370009aff23.png">
3- terraform apply
<img width="650" alt="image" src="https://user-images.githubusercontent.com/4720478/154947565-3495cb2b-1555-4a39-bfe7-0c21231ef9fd.png">

As far as I get, it is taking the latest version of provider. There was no need for editing the HCL because I wasn't specifying a specific version in the last example and it took the latest one by default.

**Comment by robertolopezlopez** [comment]
Well, that's rather very surprising @Fuochi. Could you please share here your complete HCL configuration? (Please, do not forget to mask the sensitive fields such as contract). We are looking very closely at this issue from the DevExp team, I can assure you.

**Comment by Fuochi** [comment]
here it is, I used variables for sensitive data 
```hcl
terraform {
  required_version = ">= 1"

  required_providers {
    akamai = {
      source = "akamai/akamai"
    }
  }
}

provider "akamai" {
    edgerc = "~/.edgerc"
}

variable "property_id" {
  type = number
}

variable "ect" {
  type = string
}

variable "connector_url" {
  type = string
}

data "akamai_groups" "this" {
}

data "akamai_contract" "this" {
  group_name = data.akamai_groups.this.groups[0].group_name
}

data "akamai_group" "this" {
  group_name  = data.akamai_groups.this.groups[0].group_name
  contract_id = data.akamai_contract.this.id
}

resource "akamai_datastream" "this" {
  active = false
  config {
    format = "JSON"
    frequency {
      time_in_sec = 60
    }
  }
  contract_id = data.akamai_contract.this.id
  dataset_fields_ids = [1002, 1005, 1006, 1008, 1009, 1100]
  email_ids     = ["test@akamai.com"]
  group_id      = data.akamai_group.this.id
  property_ids  = [var.property_id]
  stream_name   = "test"
  stream_type   = "RAW_LOGS"
  template_name = "EDGE_LOGS"

  splunk_connector {
    compress_logs         = true
    connector_name        = "Splunk"
    event_collector_token = var.ect
    url                   = var.connector_url
  }
}
```

**Comment by robertolopezlopez** [comment]
Hi @Fuochi ,

Great, now we have been able to replicate this issue :-) We will create an internal ticket and will be fixed probably in our next release. We will double check with you then, if you do not mind.

The issue is related to the config format. When we use structured, the `/datastream-config-api/v1/log/streams/{streamid}`  is returning explicit order for those dataset ids. On the contrary, when using json format, it does not. We will deal with this issue, now that we were able to reproduce.

In the meanwhile, could you please confirm that changing to `STRUCTURED` config format does fix this problem for you?

I would suggest you to use this work around in the meanwhile, but it obviously depends on the way that you consume this data and it may be not so straight forward.

Thank you once again,

Roberto

**Comment by Fuochi** [comment]
Hi @robertolopezlopez,
I confirm that with `STRUCTURED` config format the error isn't present.
I am really sorry I wasted your time with wrong information in here: https://github.com/akamai/terraform-provider-akamai/issues/287#issuecomment-1042879707

Thank you again for looking into this. I'll look forward the new release!

**Comment by robertolopezlopez** [comment]
No problem @Fuochi , we are here to help and all feedback is appreciated.

We will try to address this problem and release a fix as soon as possible.

**Comment by lkowalsk-akamai-com** [comment]
Hi, this issue should be fixed now. Please verify if reopen in case any problems.
