### ISSUE TITLE
terraform Error: Provider produced invalid plan

### ISSUE THREAD

**Issue by RosscoeP** [akamai/terraform-provider-akamai#628]
Case ID: F-CS-9638244

terraform 1.0.11,
registry.terraform.io/akamai/akamai 6.6.0,
registry.terraform.io/hashicorp/azurerm 3.81.0.

Any change to property-snippets files on a terraform plan/apply produces:-

akamai_edge_hostname.mainsite_neu: Refreshing state... [id=ehn_5857132]
akamai_edge_hostname.static_assets_neu: Refreshing state... [id=ehn_5857134]
akamai_edge_hostname.static_assets_uks: Refreshing state... [id=ehn_5857135]
akamai_edge_hostname.mainsite_uks: Refreshing state... [id=ehn_5857136]
akamai_edge_hostname.default: Refreshing state... [id=ehn_5857133]
akamai_property.ap_ukpn_bg: Refreshing state... [id=prp_1158604]
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/akamai/akamai" planned an invalid value for akamai_property.ap_ukpn_bg.rules: 
planned value
│ cty.StringVal(
.
.
.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

**Comment by KonradRajda** [comment]
Hi @RosscoeP 

I have tried to reproduce issue that you have described, but unfortunately in my case everything works as expected. Could you please provide your terraform configuration files with description which changes produce this error? 
Also we have released v7.0.0 of terraform-provider-akamai, it may be worth checking if the problem occurs in the latest version.

BR,
Konrad

**Comment by RosscoeP** [comment]
I upgraded the akamai cli:-
    brew update
    brew install akamai
upgraded the terraform plugin of akamai:-
    akamai uninstall terraform.
    akamai install terraform. 
re-exported the definitions and compared:-
    akamai terraform export-property preprod-bg-tangentlabs
Still the same error after a terraform init and terraform plan.

The last thing to try upgrading was the terraform command itself:-
    tfenv list-remote,
    tfenv install 1.11.2,
    tfenv use 1.11.2,
    terraform init -backend-config=${env}_backend.conf -reconfigure -upgrade
Followed by a terraform init and a terraform plan, then make a change and re-run the terraform plan.
It worked!

So it looks like the issue was the terraform version.

**Comment by KonradRajda** [comment]
Thanks for update @RosscoeP 
I am closing this issue.

BR,
Konrad
